spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:project
    username: "admin"
    password: "123"

server:
  address: 0.0.0.0
  port: ${PORT:8080}

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://64153fd930929ea5ab98ee4b61e76c7f@o4507437203718144.ingest.de.sentry.io/4507437206929488
  tracesSampleRate: 1.0
  exception-resolver-order: -2147483647